on: [push]

name: Pull versions from Reliza, do a test build, update version and commit

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: TODO
        run: |
          echo "TODO"