on: [push]

jobs:
  Update:
    runs-on: ubuntu-latest
    name: Build and push
    steps:
    - uses: actions/checkout@v2
    - name: Get version
      run: |
        reliza_ver=$(docker run --rm relizaio/reliza-cli getversion -i PROJECT__8d06445c-fc02-4748-9eda-a8822082c539 -k f7db60e1e6521c5558ab62fe8234765b3496a1410e98ca89b327bbcf6bf70f4d540673f195f15c5d0f5d3720f97760bb -b master)
          echo "RLZ_VER_JSON=$reliza_ver" >> $GITHUB_ENV
          echo "completed getting ver"
          echo $reliza_ver
    - name: Extract Actual Version From JSON
      run: |
        full_ver=$(echo $RLZ_VER_JSON | jq -r ".version")
        echo "RLZ_FULL_VER=$full_ver" >> $GITHUB_ENV
        echo $full_ver
    - name: Set build.gradle version
      run: |
        gradle changeVersion -Pversion="$RLZ_FULL_VER"
        gradle printVersion
    - name: Commit and push
      run: |
        git commit -am "chore: update project version to $RLZ_FULL_VER"
        git push
        
