on: [push]

jobs:
  Update:
    runs-on: ubuntu-latest
    name: Build and push
    steps:
    - uses: actions/checkout@v2
    - name: Get version
      run: |
        reliza_ver=$(docker run --rm relizaio/reliza-cli getversion -i PROJECT__8d06445c-fc02-4748-9eda-a8822082c539 \
        -k f7db60e1e6521c5558ab62fe8234765b3496a1410e98ca89b327bbcf6bf70f4d540673f195f15c5d0f5d3720f97760bb -b $GITHUB_REF)
          echo "RLZ_VER_JSON=$reliza_ver" >> $GITHUB_ENV
          echo "completed getting ver"
          echo $reliza_ver
    - name: Extract Actual Version From JSON
      run: |
        full_ver=$(echo $RLZ_VER_JSON | jq -r ".version")
        echo "RLZ_FULL_VER=$full_ver" >> $GITHUB_ENV
        echo $full_ver
    - name: Set build.gradle version
      run: |
        gradle changeVersion -Pversion="$RLZ_FULL_VER"
    - name: Commit and push
      run: |
        git config --global user.name 'Reliza'
        git config --global user.email 'info@reliza.io'
        git commit -am "chore: update project version to $RLZ_FULL_VER"
        git push
    - name: Run tests
      run: gradle test
    - name: If tests fail
      if: failure()
      run: echo "--status rejected " > reliza_command
    - name: Send release metadata
      if: always()
      run: |
        echo "-i PROJECT__8d06445c-fc02-4748-9eda-a8822082c539 -k f7db60e1e6521c5558ab62fe8234765b3496a1410e98ca89b327bbcf6bf70f4d540673f195f15c5d0f5d3720f97760bb \
        -b $GITHUB_REF --vcstype git --date $(git log -1 --date=iso-strict --pretty="%ad") --commit $(git rev-parse HEAD)
        --vcsuri github.com/$GITHUB_REPOSITORY -v $RLZ_FULL_VER" > reliza_command
        echo $(cat reliza_command)
        #send datas
        reliza_metadata=$(docker run --rm relizaio/reliza-cli addrelease $(cat reliza_command))
        echo $reliza_metadata
           