on: [push]

name: Publish to Maven Central

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    env:
      CENTRAL_USER: ${{ secrets.CENTRAL_USER }}
      CENTRAL_PASS: ${{ secrets.CENTRAL_PASS }}
      SIGN_PASS: ${{ secrets.SIGN_PASS }}
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      RELIZA_API_ID: ${{ secrets.RELIZA_API_ID }}
      RELIZA_API_KEY: ${{ secrets.RELIZA_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      # Install and setup JDK 11
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set build.gradle version
        run: gradle changeVersion -PnewVersion="${RLZ_FULL_VER}"
      - name: Run tests
        run: gradle test
      - name: If build fails
        if: failure()
        run: echo "--status rejected " > reliza_command
      - name: Extract Last Release Commit And Prepare List Of Commits
        run: |
          last_commit=$(docker run --rm relizaio/reliza-cli getlatestrelease -i ${{ secrets.RELIZA_API_ID }} -k ${{ secrets.RELIZA_API_KEY }} \
            --branch $GITHUB_REF | jq -r ".sourceCodeEntryDetails.commit")
          echo $last_commit
          if [ ! -z "$last_commit" ]
          then
            echo -n "--commits $(git log $last_commit..$GITHUB_SHA --date=iso-strict --pretty='%H|||%ad|||%s' | base64 -w 0) " >> reliza_command
            echo $(git log $last_commit..$GITHUB_SHA)
          fi
      - name: Publish to Central
        # exporting key to sign - https://stackoverflow.com/questions/57921325/gradle-signarchives-unable-to-read-secret-key/58000485#58000485
        if: success()
        run: |
          echo "GPG_SIGNING_KEY=$SIGN_KEY" > gradle.properties
          echo "GPG_SIGNING_PASSWORD=$SIGN_PASS" >> gradle.properties
          # prepare gradle.properties for signing
          gradle publishAllPublicationsToCentralRepository -PcentralUser=$CENTRAL_USER -PcentralPassword=$CENTRAL_PASS