on:
  repository_dispatch:
    types: [reliza-build-event]

name: Publish to Maven Central

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    env:
      CENTRAL_USER: ${{ secrets.CENTRAL_USER }}
      CENTRAL_PASS: ${{ secrets.CENTRAL_PASS }}
      SIGN_PASS: ${{ secrets.SIGN_PASS }}
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install and setup JDK 11
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish to Central
        # exporting key to sign - https://stackoverflow.com/questions/57921325/gradle-signarchives-unable-to-read-secret-key/58000485#58000485
        run: |
          echo "GPG_SIGNING_KEY=$SIGN_KEY" > gradle.properties
          echo "GPG_SIGNING_PASSWORD=$SIGN_PASS" >> gradle.properties
          # prepare gradle.properties for signing
          gradle publishAllPublicationsToCentralRepository -PcentralUser=$CENTRAL_USER -PcentralPassword=$CENTRAL_PASS