on:
  repository_dispatch:
    types: [reliza-build-event]

name: Publish to Maven Central

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    env:
      CENTRAL_USER: ${{ secrets.CENTRAL_USER }}
      CENTRAL_PASS: ${{ secrets.CENTRAL_PASS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install and setup JDK 11
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish to Central
        run: |
          gradle publishAllPublicationsToCentralRepository -PcentralUser=$CENTRAL_USER -PcentralPassword=$CENTRAL_PASS